"""
This file defines the SQLAlchemy database models (tables).
It imports the Base from database.py and SQLAlchemy column types.
These models map Python classes to PostgreSQL tables.
"""

from datetime import datetime

from sqlalchemy import Column, Integer, String, Float, DateTime, ForeignKey
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func

from database import Base


class Model(Base):
    """
    Represents an LLM model family/base in the database.
    """
    __tablename__ = "models"

    # Primary key, auto-incrementing ID
    id = Column(Integer, primary_key=True, autoincrement=True)
    # The human-readable name of the model (e.g. "Llama 3.2 3B")
    name = Column(String, index=True)
    # The tag used in Ollama (e.g. "llama3.2:3b")
    ollama_tag = Column(String, index=True)
    # The family of the model (e.g. "llama")
    family = Column(String)
    # Number of parameters in billions (e.g. 3.0)
    params_b = Column(Float)
    # Maximum context length in tokens (e.g. 128000)
    context_length = Column(Integer)
    # The license of the model (e.g. "llama3.2")
    licence = Column(String)
    # JSON string of tasks the model is good for (e.g. '["chat", "coding"]')
    tasks = Column(String)
    # The HuggingFace model ID for pulling stats/info
    hf_model_id = Column(String)
    # A description of the model
    description = Column(String)

    quality_score = Column(Float, default=0.5)
    downloads_last_month = Column(Integer, default=0)
    likes = Column(Integer, default=0)

    # Relationship to ModelQuant (one-to-many)
    quants = relationship("ModelQuant", back_populates="model", cascade="all, delete-orphan")
    # Relationship to BenchmarkResult (one-to-many)
    benchmarks = relationship("BenchmarkResult", back_populates="model", cascade="all, delete-orphan")


class ModelQuant(Base):
    """
    Represents a specific quantization of a model (e.g., Q4_K_M).
    """
    __tablename__ = "model_quants"

    # Primary key
    id = Column(Integer, primary_key=True, autoincrement=True)
    # Foreign key to the parent model
    model_id = Column(Integer, ForeignKey("models.id"))
    # Quantization type (e.g., "Q4_K_M")
    quant = Column(String)
    # Size of the model in GB
    size_gb = Column(Float)
    # Minimum VRAM required to run the model (GB)
    min_vram_gb = Column(Float)
    # Recommended VRAM for good performance (GB)
    rec_vram_gb = Column(Float)
    # Minimum System RAM required (GB)
    min_ram_gb = Column(Float)
    # Recommended System RAM (GB)
    rec_ram_gb = Column(Float)
    # Estimated tokens/sec on low-end GPU
    est_tps_low = Column(Float)
    # Estimated tokens/sec on mid-range GPU
    est_tps_mid = Column(Float)
    # Estimated tokens/sec on CPU only
    est_tps_cpu = Column(Float)
    # Command to pull via Ollama
    ollama_url = Column(String)
    # URL to the HuggingFace page
    hf_url = Column(String)
    # URL for direct GGUF download
    gguf_url = Column(String)

    # Relationship back to the parent model
    model = relationship("Model", back_populates="quants")


class HardwareSession(Base):
    """
    Represents a hardware scan session submitted by a user.
    """
    __tablename__ = "hardware_sessions"

    # Primary key, a UUID token generated by the backend
    token = Column(String, primary_key=True, index=True)
    # Name of the user's GPU
    gpu_name = Column(String)
    # Amount of VRAM in GB
    vram_gb = Column(Float)
    # Amount of System RAM in GB
    ram_gb = Column(Float)
    # Name of the user's CPU
    cpu_name = Column(String)
    # Number of CPU cores
    cpu_cores = Column(Integer)
    # Operating System
    os = Column(String)
    # Disk space total and free
    disk_total_gb = Column(Float, default=0.0)
    disk_free_gb = Column(Float, default=0.0)
    # When the session was created
    created_at = Column(DateTime, server_default=func.now())


class BenchmarkResult(Base):
    """
    Represents a benchmark run for a specific model quant on specific hardware.
    """
    __tablename__ = "benchmark_results"

    # Primary key
    id = Column(Integer, primary_key=True, autoincrement=True)
    # Foreign key to the model
    model_id = Column(Integer, ForeignKey("models.id"))
    # The quant used during the benchmark
    quant = Column(String)
    # GPU used for the benchmark
    gpu_name = Column(String)
    # VRAM of the GPU used
    vram_gb = Column(Float)
    # Tokens per second achieved
    tokens_per_sec = Column(Float)
    # Time to first token in milliseconds
    ttft_ms = Column(Integer)
    # Source of the benchmark ("official" or "community")
    source = Column(String)
    # When the benchmark was submitted
    submitted_at = Column(DateTime, server_default=func.now())

    # Relationship back to the model
    model = relationship("Model", back_populates="benchmarks")
